import React from 'react';
import { DecisionResult, CropType } from '../../types/storage';
import { EnvironmentalData } from '../../types/iot';

interface VerdictCardProps {
  decision: DecisionResult | null;
  crop: CropType | null;
  volume: number;
  environmentalData: EnvironmentalData;
  isLoading?: boolean;
}

const VerdictCard: React.FC<VerdictCardProps> = ({
  decision,
  crop,
  volume,
  environmentalData,
  isLoading = false
}) => {
  const generateReport = () => {
    if (!decision || !crop) return;

    // Create and download report
    const reportContent = `
SMART-SILO STORAGE REFEREE - DECISION REPORT
Generated: ${new Date().toLocaleString()}

HARVEST DETAILS:
- Crop: ${crop.name} ${crop.icon}
- Volume: ${volume} quintals
- Market Price: ₹${crop.marketPrice}/quintal
- Total Value: ₹${(crop.marketPrice * volume).toLocaleString()}

ENVIRONMENTAL CONDITIONS:
- Temperature: ${environmentalData.temperature.toFixed(1)}°C
- Humidity: ${environmentalData.humidity.toFixed(1)}%
- Recorded: ${environmentalData.timestamp.toLocaleString()}

RECOMMENDATION: ${decision.recommendedOption.type === 'cold_storage' ? 'COLD STORAGE' : 'SOLAR DRYING'}
- Estimated Profit: ₹${decision.recommendedOption.estimatedProfit.toLocaleString()}
- Confidence Level: ${decision.confidence.toFixed(1)}%
- Carbon Footprint: ${decision.recommendedOption.carbonFootprint.toUpperCase()}

COST BREAKDOWN:
- Storage Cost: ₹${decision.recommendedOption.costs.storage.toLocaleString()}
- Transport Cost: ₹${decision.recommendedOption.costs.transport.toLocaleString()}
- Energy Cost: ₹${decision.recommendedOption.costs.energy.toLocaleString()}
- Total Costs: ₹${(decision.recommendedOption.costs.storage + decision.recommendedOption.costs.transport + decision.recommendedOption.costs.energy).toLocaleString()}

EXPLANATION:
${decision.explanation}

RISK FACTORS:
- Humidity Level: ${environmentalData.humidity.toFixed(1)}%
- Distance to Storage: ${decision.factors.distance} km
- Market Price: ₹${decision.factors.marketPrice}/quintal

---
This report was generated by Smart-Silo Storage Referee
For support, contact: support@smart-silo.com
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `storage-decision-${crop.name.toLowerCase()}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="bg-white p-6 rounded-lg shadow-md border-l-4 border-gold animate-pulse">
        <div className="h-6 bg-slate-200 rounded mb-4"></div>
        <div className="space-y-3">
          <div className="h-4 bg-slate-200 rounded"></div>
          <div className="h-4 bg-slate-200 rounded w-3/4"></div>
          <div className="h-10 bg-slate-200 rounded"></div>
        </div>
      </div>
    );
  }

  if (!decision || !crop) {
    return (
      <div className="bg-white p-6 rounded-lg shadow-md border-l-4 border-slate-300">
        <h3 className="text-lg font-semibold mb-4 text-slate-700">
          Storage Recommendation
        </h3>
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-8 text-center">
          <div className="text-slate-400 text-4xl mb-4">🤖</div>
          <h4 className="font-semibold text-slate-600 mb-2">
            Awaiting Analysis
          </h4>
          <p className="text-sm text-slate-500">
            Complete your harvest parameters to receive a personalized storage recommendation
          </p>
        </div>
      </div>
    );
  }

  const getRecommendationIcon = () => {
    return decision.recommendedOption.type === 'cold_storage' ? '🏭' : '☀️';
  };

  const getRecommendationTitle = () => {
    return decision.recommendedOption.type === 'cold_storage' ? 'Cold Storage' : 'Solar Drying';
  };

  const getConfidenceColor = () => {
    if (decision.confidence >= 80) return 'text-green-600';
    if (decision.confidence >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getConfidenceBg = () => {
    if (decision.confidence >= 80) return 'bg-green-50';
    if (decision.confidence >= 60) return 'bg-yellow-50';
    return 'bg-red-50';
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-md border-l-4 border-gold">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-semibold text-slate-700">
          Storage Recommendation
        </h3>
        <div className={`
          inline-flex items-center px-3 py-1 rounded-full text-sm font-medium
          ${getConfidenceBg()} ${getConfidenceColor()}
        `}>
          {decision.confidence.toFixed(0)}% Confidence
        </div>
      </div>

      {/* Recommendation */}
      <div className="mb-6">
        <div className="flex items-center space-x-4 mb-4">
          <div className="text-4xl">{getRecommendationIcon()}</div>
          <div>
            <h4 className="text-2xl font-bold text-slate-800">
              {getRecommendationTitle()}
            </h4>
            <p className="text-slate-600">
              Estimated profit: <span className="font-semibold text-green-600">
                ₹{decision.recommendedOption.estimatedProfit.toLocaleString()}
              </span>
            </p>
          </div>
        </div>

        {/* Explanation */}
        <div className="bg-slate-50 rounded-lg p-4 mb-4">
          <h5 className="font-semibold text-slate-700 mb-2">Why this recommendation?</h5>
          <p className="text-slate-700 leading-relaxed">
            {decision.explanation}
          </p>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="bg-blue-50 p-4 rounded-lg">
          <div className="text-blue-600 text-sm font-medium">Environmental Risk</div>
          <div className="text-blue-800 font-semibold">
            {environmentalData.humidity <= 65 ? 'Low' : 
             environmentalData.humidity <= 80 ? 'Medium' : 'High'}
          </div>
          <div className="text-blue-600 text-xs">
            {environmentalData.humidity.toFixed(1)}% humidity
          </div>
        </div>

        <div className="bg-green-50 p-4 rounded-lg">
          <div className="text-green-600 text-sm font-medium">Carbon Impact</div>
          <div className="text-green-800 font-semibold">
            {decision.recommendedOption.carbonFootprint === 'zero' ? 'Zero Emissions' : 'High Emissions'}
          </div>
          <div className="text-green-600 text-xs">
            {decision.recommendedOption.carbonFootprint === 'zero' ? 'Solar powered' : 'Grid electricity'}
          </div>
        </div>

        <div className="bg-purple-50 p-4 rounded-lg">
          <div className="text-purple-600 text-sm font-medium">Total Investment</div>
          <div className="text-purple-800 font-semibold">
            ₹{(decision.recommendedOption.costs.storage + 
               decision.recommendedOption.costs.transport + 
               decision.recommendedOption.costs.energy).toLocaleString()}
          </div>
          <div className="text-purple-600 text-xs">
            All operational costs
          </div>
        </div>
      </div>

      {/* Risk Penalty Warning (for solar drying) */}
      {decision.recommendedOption.type === 'solar_drying' && decision.recommendedOption.riskPenalty > 10 && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
          <div className="flex items-center mb-2">
            <div className="text-yellow-600 mr-2">⚠️</div>
            <h5 className="font-semibold text-yellow-800">Environmental Risk Notice</h5>
          </div>
          <p className="text-sm text-yellow-700">
            Current humidity levels ({environmentalData.humidity.toFixed(1)}%) create a {decision.recommendedOption.riskPenalty.toFixed(1)}% 
            risk penalty. Monitor weather conditions closely and consider backup plans.
          </p>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={generateReport}
          className="flex-1 bg-gold text-white py-3 px-6 rounded-lg font-semibold hover:bg-yellow-600 transition-colors flex items-center justify-center space-x-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span>Download Decision Report</span>
        </button>
        
        <button
          onClick={() => window.print()}
          className="bg-slate-600 text-white py-3 px-6 rounded-lg font-semibold hover:bg-slate-700 transition-colors flex items-center justify-center space-x-2"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          <span>Print</span>
        </button>
      </div>

      {/* Footer */}
      <div className="mt-6 pt-4 border-t border-slate-200 text-xs text-slate-500 text-center">
        Decision generated at {new Date().toLocaleString()} • 
        Based on current market conditions and environmental data • 
        Recommendations subject to market volatility
      </div>
    </div>
  );
};

export default VerdictCard;